### ISSUE TITLE
[Bug] elytra in non-combat mode

### ISSUE THREAD

**Issue by Im-ZGhosty** [timderspieler/DeluxeCombat-Issues#34]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

This server is running Paper version git-Paper-256 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e30b082)

### Your discord name

ImZGhosty#2707

### Current Behavior

It is with DeluxeCombat that I have given the option of not using elytra in combat, this does it well, when he tags a user the elytra is automatically removed and left in his inventory, the problem is that when he does this remove event the elitra for some reason this user can no longer be hit or hit (like it gives him a few seconds of grace which he can take advantage of to run and escape)

### Expected Behavior

I was looking for him to cancel using elytras in combat to prevent them from escaping mid-fight but activating this event makes them give them another chance because when they have that grace time they can run away and being at a sufficient distance exit the combatlog and go with elytras again

### Steps To Reproduce

1. Activate combatlog
2. One of both must try to use the elytra
3. Attempting to hit the user who tried to use the elytra

### Frequency

This always happens

### Anything else?

https://www.youtube.com/watch?v=Y4nLz7Fp0wE

**Comment by timderspieler** [comment]
Hello @Im-ZGhosty ,

this is a known issue related to Essentials. Please open your essentials config and search for the option "Teleport Invulnerability" and disable it.

DeluxeCombat has to teleport the player that used an elytren a tiny bit in order to cancel the flight. Essentials catches this and gives that player an invulnerability effect.

If you disable the mentioned option, the issue should be gone :)

greetings
